export const CardsIcon = () => (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect
      x="2"
      y="3"
      width="15"
      height="13"
      rx="2"
      stroke="white"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <path
      d="M7 21H19C20.1046 21 21 20.1046 21 19V8"
      stroke="white"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    <line
      x1="6"
      y1="7"
      x2="13"
      y2="7"
      stroke="white"
      strokeWidth="2"
      strokeLinecap="round"
    />
    <line
      x1="6"
      y1="10.5"
      x2="10"
      y2="10.5"
      stroke="white"
      strokeWidth="2"
      strokeLinecap="round"
    />
  </svg>
);
