export const wallets = [{id:'card', name:'Основна картка', currency:'UAH', balance:18450, createdAt:1},{id:'travel', name:'Подорожі', currency:'EUR', balance:320, createdAt:2}];
export let settings = { currency:'UAH', mainWalletId:'card', budgetLimit:12000, smartGoals:[{id:'goal', title:'Подорож до моря',targetAmount:30000,savedAmount:12500,currency:'UAH',createdAt:1}], payday:{date:'2026-09-25',reserve:5000,currency:'UAH',walletIds:['card']} };
const transactions = [{ id:'tx1',type:'expense',amount:245,category:'food',description:'Сільпо',date:Date.now(),month:'2026-09',currency:'UAH',walletId:'card',tags:['продукти'] },{id:'tx2',type:'expense',amount:80,category:'cafe',description:'Кава',date:Date.now(),month:'2026-09',currency:'UAH',walletId:'card',tags:['місто']}];
const listeners = new Set();
const subscribe = (value, args) => { const fn = args.find(arg => typeof arg === 'function'); fn?.(value); return () => {}; };
const subscribeSettings = (...args) => { const fn = args.find(arg => typeof arg === 'function'); listeners.add(fn); fn?.(settings); return () => listeners.delete(fn); };
export { calculateWalletBalanceAfterTransaction } from '../../src/domain/finance';
export const ADMIN_TELEGRAM_ID = 0;
export const ACTIVE_SESSION_STALE_MS = 45000;
export const onTransactionsChanged = async () => null;
export const getCurrentMonth = () => '2026-09';
export const SHARE_CODE_PATTERN = /^[a-z]+$/;
export const isValidShareCode = async () => null;
export const isValidTelegramUserId = async () => null;
export const registerUser = async () => null;
export const getUserData = async () => null;
export const subscribeToActiveSession = (...args) => subscribe([], args);
export const claimActiveSession = async () => null;
export const updateActiveSessionHeartbeat = async () => null;
export const releaseActiveSession = async () => null;
export const subscribeToAdminStats = (...args) => subscribe([], args);
export const setMonthlyBalance = async () => null;
export const addWalletBalance = async () => null;
export const deleteWalletData = async () => null;
export const getMonthlyBalance = async () => null;
export const addWallet = async () => null;
export const updateWallet = async () => null;
export const deleteWallet = async () => null;
export const subscribeToWallets = (...args) => subscribe(wallets, args);
export const getWallets = async () => wallets;
export const addTransaction = async () => null;
export const reconcileWallet = async () => null;
export const addTransfer = async () => null;
export const getTransactions = async () => null;
export const updateTransaction = async () => null;
export const deleteTransaction = async () => null;
export const restoreDeletedTransaction = async () => null;
export const getSharedReceipt = async () => null;
export const getUserQrPayload = async () => null;
export const parseUserQrPayload = async () => null;
export const getOrCreateTemporaryUserCode = async () => null;
export const getParticipantByTemporaryCode = async () => null;
export const getExistingShare = async () => null;
export const createReceiptShare = async () => null;
export const getReceiptShare = async () => null;
export const getShareStatus = async () => null;
export const toggleReceiptShare = async () => null;
export const saveSharedReceipt = async () => null;
export const unsaveSharedReceipt = async () => null;
export const subscribeToSavedReceipts = (...args) => subscribe([], args);
export const getReceiptSavers = async () => null;
export const checkIfSavedByMe = async () => null;
export const createJointCheck = async () => null;
export const subscribeToJointCheck = (...args) => subscribe([], args);
export const subscribeToTransactions = (...args) => subscribe(transactions, args);
export const subscribeToAllTransactions = (...args) => subscribe(transactions, args);
export const subscribeToMonthlyBalance = (...args) => subscribe([], args);
export const subscribeToSettings = subscribeSettings;
export const getUserSettings = async () => settings;
export const deleteSmartGoal = async () => null;
export const updateUserSettings = async (_id, patch) => { settings = {...settings,...patch}; listeners.forEach(fn=>fn(settings)); };
export const subscribeToUserSettings = subscribeSettings;
export const getAllTransactions = async () => null;
export const addSubscription = async () => null;
export const updateSubscription = async () => null;
export const deleteSubscription = async () => null;
export const subscribeToSubscriptions = (...args) => subscribe([], args);
export const incrementVendorUsage = async () => null;
export const deleteUserAccount = async () => null;
